# **Movies Recomendation System**

In [35]:
import pandas as pd

In [36]:
df= pd.read_csv('Movies_data.csv')
df.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10000 non-null  int64
 1   title              10000 non-null  object
 2   genre              9997 non-null   object
 3   original_language  10000 non-null  object
 4   overview           9987 non-null   object
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 703.3+ KB

# Feature Selection

In [38]:
df.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [39]:
# Select important feature Necessary for recomendation system
df = df[['id', 'title', 'genre', 'overview']]

In [40]:
df['tags'] = df['overview'] +df['genre']
df.head(2)

,id,title,genre,overview,tags
0,278,The Shawshank Redemption,"Drama,Crime",Framed in the 1940s for the double murder of h...,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance","Raj is a rich, carefree, happy-go-lucky second...","Raj is a rich, carefree, happy-go-lucky second..."

In [41]:
df = df[['id','title','tags']]
df.head()

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...

# Implementation

In [42]:
from sklearn.feature_extraction.text import CountVectorizer

In [43]:
# vectorizing the tags varibles
cv = CountVectorizer(max_features=10000,stop_words='english')

In [45]:
vector = cv.fit_transform(df['tags'].values.astype('U'))

In [46]:
from sklearn.metrics.pairwise import cosine_similarity

In [47]:
# using the cosine similarity to find the similarity between records (sparse output to save memory)
similarity = cosine_similarity(vector)
vector

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 237256 stored elements and shape (10000, 10000)>

In [49]:
def recommend(movies):
    index = df[df['title']==movies].index[0]
    distance = sorted(list(enumerate(similarity[index])),reverse=True,key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(df.loc[i[0]]['title'])

In [50]:
recommend('John Wick')

John Wick
John Wick: Chapter 2
John Wick: Chapter 3 - Parabellum
The Getaway
The Night Comes for Us

In [51]:
import pickle

In [52]:
pickle.dump(df, open('movies_list.pkl', 'wb'))

In [53]:
pickle.dump(similarity,open('similarity.pkl', 'wb'))